[WIP]基礎構築
human-osaka-game-2018/kawahara_shooting pull request #12
Opened 2019-02-20 03:28 UTC by koujiroukawahara

ゲームシーンを１つだけにし、ゲームシーンのUpdateとRenderを通る様にする
(今はゲームシーンだけだが本来はその時にシーンのUpdateとRenderが通る)
Closes #11

2019-02-20 06:50 UTC, koujiroukawahara commented
レビューしてほしいです　

2019-02-20 13:03 UTC, taishi-matsumura requested changes
質問に対しては回答を、指摘に対しては回答と是正をお願いします。
ヨロシク！

2019-02-20 13:03 UTC, taishi-matsumura commented on XEVIOUS/ProjectManager.h
> +	void m_OnFinisedhDrawing();
```suggestion
	void m_OnFinishedDrawing();
```
やね。

2019-02-20 13:03 UTC, taishi-matsumura commented on XEVIOUS/GameScene.h
> +};
行末に改行入れる癖を付けましょう。
他のファイルも同様。

2019-02-20 13:03 UTC, taishi-matsumura commented on XEVIOUS/ProjectManager.h
> +	void m_OnFinisedhDrawing();
関数名に `m_` 付けてるコードは見たことが無いです。
それでいくなら構いませんが、だったら全部それで統一して下さい。

2019-02-20 13:03 UTC, taishi-matsumura commented on XEVIOUS/SceneManager.h
> +	static Scene*	m_pScene;
```suggestion
	static Scene* m_pScene;
```
スペースじゃなくてタブ文字が入ってませんか？

2019-02-20 13:03 UTC, taishi-matsumura commented on XEVIOUS/SceneManager.h
> +	//���̃V�[��
日本語コメントが化けるのでUTF-8にしてもらえると嬉しいです。
ってか、しましょう。

2019-02-20 13:03 UTC, taishi-matsumura commented on XEVIOUS/ProjectManager.cpp
> +	m_pSceneManager = new SceneManager();
いつ、誰がdeleteするの？
そもそも、動的確保する必要ありますか？

2019-02-20 13:03 UTC, taishi-matsumura commented on XEVIOUS/ProjectManager.h
> +	static SceneManager* m_pSceneManager;
こいつらを`static`にしている理由は？

2019-02-20 13:03 UTC, taishi-matsumura commented on XEVIOUS/SceneManager.h
> +	static Scene*	m_pScene;
なぜ`static`？

2019-02-20 13:03 UTC, taishi-matsumura commented on XEVIOUS/Scene.h
> +#include "enum_Scene.h"
他のファイルと並べたときにファイル名の付け方が全然違うので気持ち悪いですね。

2019-02-20 13:03 UTC, taishi-matsumura commented on XEVIOUS/Scene.h
> +public:
新規クラス作った瞬間にc'torとd'tor書く癖を付けて下さい。

2019-02-21 01:34 UTC, ToshiyaMatsuoka commented on XEVIOUS/ProjectManager.h
> +	void m_OnFinisedhDrawing();
`m_`のある2つの関数について、`On`入りますか？
翻訳かけたら「載って、スケッチを準備してください」とか
「完結したスケッチに関して」など関数として意味わからない訳になったのですが

2019-02-21 06:22 UTC, koujiroukawahara commented on XEVIOUS/ProjectManager.h
> +	void m_OnFinisedhDrawing();
ありがとうございます

2019-02-21 06:26 UTC, koujiroukawahara commented on XEVIOUS/GameScene.h
> +};
了解です
直しました

2019-02-21 06:29 UTC, koujiroukawahara commented on XEVIOUS/ProjectManager.h
> +	void m_OnFinisedhDrawing();
関数にｍ＿が要らない理由を辻野に聞いて納得したので外します
すがおさんにOnは～をする時と聞いたので描画する時と描画終了する時に使おうと思ったのでOnを使いました

2019-02-21 06:33 UTC, taishi-matsumura commented on XEVIOUS/ProjectManager.h
> +	void m_OnFinisedhDrawing();
@ToshiyaMatsuoka 頭にOnが付いたメソッド名は「〜した時」という感じですね。
[このサイト](
https://qiita.com/KeithYokoma/items/2193cf79ba76563e3db)の「コールバック」とかが近いかな。

2019-02-21 06:39 UTC, koujiroukawahara commented on XEVIOUS/SceneManager.h
> +	static Scene*	m_pScene;
staticで定義したらその変数の中身がどのインスタンスでも同じと聞いたのでstatic付けたのですが、シーンが切り替わる時にm_pSceneをdeleteした直後にすぐ次のシーンをnewするので中身が同じとか意味がなかったです
staticを外しても処理が同じだったので外しときます

2019-02-21 06:40 UTC, koujiroukawahara commented on XEVIOUS/SceneManager.h
> +	//���̃V�[��
コメントは変数と関数の役割を書く以外にコメント書くことってありますか？

2019-02-21 06:45 UTC, taishi-matsumura commented on XEVIOUS/SceneManager.h
> +	//���̃V�[��
GitHubやSourceTreeで表示したときに文字化けするのでShiftJISはイヤです。

2019-02-21 06:47 UTC, koujiroukawahara commented on XEVIOUS/ProjectManager.cpp
> +	m_pSceneManager = new SceneManager();
クラスを使うのに固定概念でnewしないと使えないと考えてました
ここでは動的じゃなくても大丈夫でしたので直しました

2019-02-21 06:48 UTC, koujiroukawahara commented on XEVIOUS/ProjectManager.h
> +	static SceneManager* m_pSceneManager;
HWNDの方は使ってなかったので消しました
SceneManager* m_pSceneManagerの方も静的にしたので消しました

2019-02-21 06:51 UTC, koujiroukawahara commented on XEVIOUS/Scene.h
> +#include "enum_Scene.h"
enum_Sceneだけ_が入ってたりする所は忍者屋敷の時にやったやり方でシーン遷移を行おうとして名前をそのままコピってしまってこんなことになってしまいました
enumScene.hでどうでしょうか？

2019-02-21 06:54 UTC, ToshiyaMatsuoka commented on XEVIOUS/ProjectManager.h
> +	void m_OnFinisedhDrawing();
@taishi-matsumura 
@koujiroukawahara 
そういう意味なんですね。
ありがとうございます。

2019-02-21 06:55 UTC, koujiroukawahara commented on XEVIOUS/Scene.h
> +public:
わかりました気をつけます

2019-02-21 09:20 UTC, taishi-matsumura commented on XEVIOUS/Scene.h
> +#include "enum_Scene.h"
キモいけど、まぁ良かろう。

2019-02-21 09:33 UTC, taishi-matsumura commented on XEVIOUS/Scene.h
> +	~Scene();
基底クラスのd'torは仮想関数にしなくていいですか？
下記、それぞれ長所・短所が表裏一体ですが方針を決めて下さい。

||長所|短所|
|---|---|---|
|d'torには無条件に`virtual`付ける|派生クラスのd'torが確実に呼ばれる|継承されないクラスにとってはv-tableの分メモリが無駄|
|必要になったときだけ基底クラスのd'torに`virtual`付ける|メモリ使用量を削減できる|付け忘れてメモリリークやバグの元となる可能性アリ|

2019-02-21 09:39 UTC, taishi-matsumura requested changes

2019-02-21 09:39 UTC, taishi-matsumura commented on XEVIOUS/ProjectManager.cpp
> +void ProjectManager::OnPrepareDrawing()
菅尾先生は「開始/終了したよー」という通知を受けて何か処理をする関数かと思って「On〜」という関数名を提案してくれたのだと思うのですが、中身を見ると「描画の開始/修了時に必ず行う処理」のようですね。
であれば、 `PrepareDrawing()` (描画の準備)と `FinalizeDrawing()` (描画の仕上げ) みたいな名前の方が適切かも。

@masami-sugao @yttmwork どうでしょう？

2019-02-21 09:39 UTC, taishi-matsumura commented on XEVIOUS/enumScene.h
> +};
改行入れときましょう。

2019-02-21 10:51 UTC, yttmwork commented on XEVIOUS/ProjectManager.cpp
> +void ProjectManager::OnPrepareDrawing()
英語は不慣れではありますが、確かにUnityなどを含めてOnはイベントなどで
呼ばれるメソッドで使用されているイメージがありますので、
今回の内容でしたらOnなしの方がいい気がします。

2019-02-21 12:11 UTC, masami-sugao commented on XEVIOUS/ProjectManager.cpp
> +void ProjectManager::OnPrepareDrawing()
そういうことだったのですね。
であればそのメソッド名がよいと思います。

2019-02-21 16:13 UTC, taishi-matsumura commented on XEVIOUS/ProjectManager.cpp
> +void ProjectManager::OnPrepareDrawing()
@yttmwork コメントあざ〜す！
えーと、
* Onは不要
* メソッド名自体は(英語苦手なので)ノーコメント

ということでOKですかね？

@masami-sugao  🙆‍♂️ 

@koujiroukawahara 他の人からはコメント無いですし、 `PrepareDrawing()` と `FinalizeDrawing()` でいきましょう！

2019-02-21 16:15 UTC, taishi-matsumura commented on XEVIOUS/Scene.h
> +	~Scene();
> 継承したデストラクタを仮想関数にするの忘れてました。これはしなくちゃダメなやつと思うので直します

了解です。
Slackじゃなくて、こっちに返信してね〜

2019-02-21 16:18 UTC, taishi-matsumura commented
各指摘に対して是正コミットが分かれていてgoodです 👍 
コミットコメントについては、[辻野への指摘](https://github.com/human-osaka-game-2018/DirectXLibrary/pull/7#issuecomment-465962089)を確認して今後は川原も同様に対応して下さい。

2019-02-21 16:23 UTC, taishi-matsumura commented on XEVIOUS/ProjectManager.cpp
> +void ProjectManager::OnPrepareDrawing()
下記やり取りもSlackから転記しておきます。

Q. (川原)
> Onは描画する時に必要とかに使うのではなく、もし描画されなかった時この関数を通るみたいな時に使うのですか？

A. (松村)
> 「されなかった時」では無いです。
`OnPrepare` は「『準備ができたよ』って言われたときに何かをする関数」、 
`Prepare` は「準備をする関数」
って感じでしょうか。
ニュアンスの違い、わかります…？

2019-02-21 18:03 UTC, yttmwork commented on XEVIOUS/ProjectManager.cpp
> +void ProjectManager::OnPrepareDrawing()
@taishi-matsumura OKです。

2019-02-22 06:58 UTC, koujiroukawahara commented on XEVIOUS/enumScene.h
> +};
なおしました

2019-02-22 06:59 UTC, taishi-matsumura approved these changes

2019-02-22 07:00 UTC, taishi-matsumura requested changes
是正確認しました。コミットの履歴を綺麗に纏めたら連絡下さい。

2019-02-22 11:30 UTC, Harutaka-Tsujino requested changes

2019-02-22 11:30 UTC, Harutaka-Tsujino commented on XEVIOUS/ProjectManager.cpp
> +				FinishedDrawing();
```suggestion
				FinishDrawing();
```

2019-02-25 06:57 UTC, taishi-matsumura commented on XEVIOUS/ProjectManager.cpp
> +				FinishedDrawing();
@Harutaka-Tsujino [先のやり取り](https://github.com/human-osaka-game-2018/kawahara_shooting/pull/12#pullrequestreview-206204119) で `Finalize` でいこうかという方針になっています。議論の流れを確認してみて下さい。

2019-02-25 08:00 UTC, taishi-matsumura approved these changes

2019-02-25 08:01 UTC, taishi-matsumura commented
@Harutaka-Tsujino 問題無ければ承認→Mergeお願いします！

2019-02-25 09:31 UTC, Harutaka-Tsujino commented on XEVIOUS/ProjectManager.cpp
> +				FinishedDrawing();
確認しました

2019-02-25 09:31 UTC, Harutaka-Tsujino approved these changes
確認しました

2019-02-25 09:31 UTC, merged