自機の描画と操作
human-osaka-game-2018/kawahara_shooting pull request #13
Opened 2019-02-20 07:08 UTC by koujiroukawahara

自機を描画し、その自機を矢印キーで動かせる様にする

2019-02-28 09:44 UTC, Harutaka-Tsujino requested changes

2019-02-28 09:44 UTC, Harutaka-Tsujino commented on XEVIOUS/DirectX.cpp
> +	float InitCustomVertexPosX03 = CenterPlayerPosX - Size;
03は何を意味するものか分からないです

2019-02-28 09:44 UTC, Harutaka-Tsujino commented on XEVIOUS/DirectX.cpp
> +	InitCustomVertex[0].x += pMovement->x;
for文で回してください

2019-02-28 09:44 UTC, Harutaka-Tsujino commented on XEVIOUS/DirectX.cpp
> +	if (m_diks[dik] &0x80)
```suggestion
	if (m_diks[dik] & 0x80)
```

2019-02-28 09:44 UTC, Harutaka-Tsujino commented on XEVIOUS/DirectX.h
> +};
改行してください

2019-02-28 09:44 UTC, Harutaka-Tsujino commented on XEVIOUS/GamePlayer.cpp
> +	D3DXVECTOR2 MoveDirection;
D3DXVECTOR2 MoveDirection(0.0f, 0.0f)
またはMoveDirection = { 0.0f, 0.0f }
等にしてはどうでしょうか？

2019-02-28 09:44 UTC, Harutaka-Tsujino commented on XEVIOUS/GamePlayer.cpp
> +	MoveDirection *= 5.f;
さすがにコメントは必要だと思います

2019-02-28 09:44 UTC, Harutaka-Tsujino commented on XEVIOUS/GamePlayer.h
> +#define PlayerSize 32.f
defineを脱却してください

2019-02-28 09:44 UTC, Harutaka-Tsujino commented on XEVIOUS/GameScene.cpp
> +	InfoGameBG InfoGameBG;
型名と変数名が同じなので修正したほうがいいともいます

2019-02-28 09:44 UTC, Harutaka-Tsujino commented on XEVIOUS/ProjectManager.cpp
> +				m_pDirectX->m_hr = m_pDirectX->m_pKeyDevice->Acquire();
ここの関数をまとめてほしいです

2019-02-28 09:44 UTC, Harutaka-Tsujino commented on XEVIOUS/ProjectManager.h.bak
> +<<<<<<< HEAD
ここ修正してください

2019-02-28 09:46 UTC, taishi-matsumura requested changes
不要なファイルがいっぱいあってレビューし辛いです。
消して下さい。

2019-03-02 05:20 UTC, koujiroukawahara commented on XEVIOUS/DirectX.cpp
> +	float InitCustomVertexPosX03 = CenterPlayerPosX - Size;
変更しました

2019-03-02 05:24 UTC, koujiroukawahara commented on XEVIOUS/DirectX.cpp
> +	InitCustomVertex[0].x += pMovement->x;
for文にしました

2019-03-02 05:24 UTC, koujiroukawahara commented on XEVIOUS/DirectX.cpp
> +	if (m_diks[dik] &0x80)
スペースを空けました

2019-03-02 05:24 UTC, koujiroukawahara commented on XEVIOUS/DirectX.h
> +};
改行しました

2019-03-02 05:26 UTC, koujiroukawahara commented on XEVIOUS/GamePlayer.cpp
> +	D3DXVECTOR2 MoveDirection;
行数が少なくなるのでそうしました

2019-03-02 05:33 UTC, koujiroukawahara commented on XEVIOUS/GamePlayer.cpp
> +	MoveDirection *= 5.f;
コメントと付けないとPlayerの速度とわからなかったのでPlayerの速度の変数をGamePlayerのメンバ変数に作りました

2019-03-02 05:35 UTC, koujiroukawahara commented on XEVIOUS/GamePlayer.h
> +#define PlayerSize 32.f
const float型にしました
DISPLAYのサイズなどもconstにした方がいい？

2019-03-02 05:39 UTC, koujiroukawahara commented on XEVIOUS/GameScene.cpp
> +	InfoGameBG InfoGameBG;
昨日説明で気持ち悪いと思ったのでなおしました

2019-03-02 05:46 UTC, koujiroukawahara commented on XEVIOUS/ProjectManager.cpp
> +				m_pDirectX->m_hr = m_pDirectX->m_pKeyDevice->Acquire();
関数にしました

2019-03-02 05:48 UTC, koujiroukawahara commented
プルリク修正を1つ、1つコミットのはずがコミットし忘れててまとめてプルリク修正でコミットしてしまいました。

2019-03-02 10:06 UTC, Harutaka-Tsujino commented on XEVIOUS/GamePlayer.h
> +#define PlayerSize 32.f
できるならばそうしたほうがいいですが
全体的に画面サイズは使うのでそこはDefineでも問題ないとは思います

2019-03-02 22:45 UTC, Harutaka-Tsujino approved these changes

2019-03-03 10:01 UTC, taishi-matsumura requested changes
レビューが遅くなってすみません。
対応お願いします。

2019-03-03 10:01 UTC, taishi-matsumura commented on XEVIOUS/DirectX.cpp
> +void DirectX::KeyGetFuncton()
これは「キーの状態を取得する関数」ですか…？
クソみたいな名前ですね 💩

2019-03-03 10:01 UTC, taishi-matsumura commented on XEVIOUS/DirectX.cpp
> +		InitCustomVertex[i].x += pMovement->x;
「移動量」で検索して「movement」という単語を見付けたのだと思いますが、「movement」だけだと「移動」なので「量」が抜けていますね。
で、移動であることは関数名からわかるので、引数にはむしろ「量」だけで良いのでは？

[ここ](https://ejje.weblio.jp/content/移動量) とかで例文を見ると、 `amount` や `quantity` が用いられていることがわかるはず。それぞれの意味と読み方は調べて下さい。

2019-03-03 10:01 UTC, taishi-matsumura commented on XEVIOUS/DirectX.cpp
> +	float InitCustomVertexPosXLeftSide = CenterPlayerPosX - Size;
今更ですが、クラス名や関数名だけじゃなく仮引数もローカル変数も全てPascalCaseでいくの？！
その理由を教えて下さい。

2019-03-03 10:01 UTC, taishi-matsumura commented on XEVIOUS/DirectX.cpp
> +	float InitCustomVertexPosYUnderSide = CenterPlayerPosY + Size;
左右ならX座標だし、上下ならY座標であることは明らかなので、こんな冗長な名前にしなくても良いと思いますよ。
`left` `right` `top` `bottom` の4つで良くない？

2019-03-03 10:01 UTC, taishi-matsumura commented on XEVIOUS/GamePlayer.cpp
> +	m_pDirectX = DirectX::GetInstance();
一旦NULLで初期化する意味は？

2019-03-03 10:01 UTC, taishi-matsumura commented on XEVIOUS/DirectX.cpp
> +		m_pInstance = new DirectX();
いつ・誰が解放するのですか？

2019-03-03 10:01 UTC, taishi-matsumura commented on XEVIOUS/GamePlayer.cpp
> +		m_pDirectX ->InitSquareCustomVertex(m_Player, OUT_OF_STAGE + (PlayerSize / 2),m_Player[0].y + (PlayerSize / 2), PlayerSize);
`OUT_OF_STAGE + (PlayerSize / 2)` とか `m_Player[0].y + (PlayerSize / 2)` が何を計算してるのかわからないし、`InitSquareCustomVertex()` の引数の中身が長くて読む気しないので、いちどローカル変数に受けて欲しいです。

2019-03-03 10:02 UTC, taishi-matsumura commented
正式にレビュー依頼出せる状態なのであれば、タイトルから「Work In Progress」を外して下さい。

2019-03-03 10:30 UTC, taishi-matsumura requested changes

2019-03-03 10:30 UTC, taishi-matsumura commented on XEVIOUS/DirectX.cpp
> +void DirectX::InitSquareCustomVertex(CustomVertex InitCustomVertex[4],float CenterPlayerPosX, float CenterPlayerPosY,float Size)
これは正方形の頂点設定関数ですよね？
正方形は長方形の特殊なパターンのはずなので、この関数から `InitRectangleCustomVertex()` を呼び出すようにして重複コードを減らして下さい。

2019-03-03 10:31 UTC, taishi-matsumura commented
グラフィックデバイスやインプットデバイスの初期化とかをどこでやっているのかが不思議だったのですが、メイン関数の中でやっているのですね…

`pProjectManager.m_pDirectX->m_pD3Device->SetRenderState()` みたいに `.` や `->` で数珠繋ぎするコードを書いたらダメです 💩 
せっかくクラスを作ったのだから、そこに委譲するようにしていって下さい。
このプルリクがだいぶ大きくなってきているので、別途プルリク作ってそっちでやるべきかも知れませんね。

2019-03-04 19:15 UTC, koujiroukawahara commented on XEVIOUS/DirectX.cpp
> +void DirectX::KeyGetFuncton()
GetKeyStateとかはどうでしょうか？

2019-03-04 19:23 UTC, koujiroukawahara commented on XEVIOUS/DirectX.cpp
> +		InitCustomVertex[i].x += pMovement->x;
この値は動かす量という意味なのでpMoveQuantityでどうでしょうか？

2019-03-04 19:28 UTC, koujiroukawahara commented on XEVIOUS/DirectX.cpp
> +	float InitCustomVertexPosXLeftSide = CenterPlayerPosX - Size;
う～ん理由は特にないです
やっぱりローカル変数はローワーとかconstのグローバル変数はスネークとか
メンバ変数はアッパーみたいに分けた方がいいですか？

2019-03-04 19:31 UTC, koujiroukawahara commented on XEVIOUS/DirectX.cpp
> +	float InitCustomVertexPosYUnderSide = CenterPlayerPosY + Size;
InitCustomVertexPosXLeftSideならInitCustomVertexLeftSideって感じでいいですか？

2019-03-04 19:34 UTC, koujiroukawahara commented on XEVIOUS/GamePlayer.cpp
> +	m_pDirectX = DirectX::GetInstance();
意味ないかも知れないですがNULLが入っていたらnewされてないってわかると思って

2019-03-04 20:37 UTC, koujiroukawahara commented on XEVIOUS/DirectX.cpp
> +		m_pInstance = new DirectX();
ProjectManagerのFreeDxでやる予定でした

2019-03-04 23:23 UTC, taishi-matsumura commented on XEVIOUS/DirectX.cpp
> +void DirectX::KeyGetFuncton()
オッケーです👌

2019-03-04 23:24 UTC, taishi-matsumura commented on XEVIOUS/DirectX.cpp
> +	float InitCustomVertexPosXLeftSide = CenterPlayerPosX - Size;
はい、分けた方が良いです。
命名基準は言語によって色々文化があるので調べて決めて下さい。

2019-03-04 23:24 UTC, taishi-matsumura commented on XEVIOUS/DirectX.cpp
> +	float InitCustomVertexPosXLeftSide = CenterPlayerPosX - Size;
はい、分けた方が良いです。
命名基準は言語によって色々文化があるので調べて決めて下さい。

2019-03-04 23:26 UTC, taishi-matsumura commented on XEVIOUS/DirectX.cpp
> +	float InitCustomVertexPosYUnderSide = CenterPlayerPosY + Size;
いや、ローカル変数ですし左なら `left` だけで良いと思います。

2019-03-04 23:27 UTC, taishi-matsumura commented on XEVIOUS/DirectX.cpp
> +		m_pInstance = new DirectX();
了解です。
こういうのは作業を分けると忘れがちなので、生成/確保と破棄/解放は必ずセットで作業するようにして下さい。

2019-03-04 23:29 UTC, taishi-matsumura commented on XEVIOUS/DirectX.cpp
> +		InitCustomVertex[i].x += pMovement->x;
それでも問題無いですが、 `quantity` だけで十分だと思います。
ついでにですが、rectとかpointとかの小さい構造体は、例外的に(ポインタ渡しではなく)値渡しが一般的だったりします。

2019-03-04 23:29 UTC, taishi-matsumura commented on XEVIOUS/GamePlayer.cpp
> +	m_pDirectX = DirectX::GetInstance();
意味無いですね。

2019-03-05 08:57 UTC, taishi-matsumura requested changes

2019-03-05 08:57 UTC, taishi-matsumura commented on XEVIOUS/ProjectManager.cpp
> +	free(DirectX::GetInstance());
`free()` って、C言語のfree？？
こんなんダメです！！！！

2019-03-05 08:57 UTC, taishi-matsumura commented on XEVIOUS/DirectX.cpp
> +	float under = CenterPlayerPosY + Size;
upper/under よりも top/bottom の方が一般的かなぁ

2019-03-05 09:17 UTC, taishi-matsumura requested changes

2019-03-05 09:17 UTC, taishi-matsumura commented on XEVIOUS/DirectX.cpp
> +	delete m_pInstance;
`DeleteInstence()` の後で再度 `GetInstance()` を呼ぶと破棄済みのインスタンスのアドレスが取得できてしまうし、 `DeleteInstence()` を連続して呼ぶと二重deleteで死にますね。

なので、ここは `m_pInstance  = NULL;` を書いておいた方が良いですね。

2019-03-05 12:55 UTC, taishi-matsumura requested changes
叩けばナンボでも埃出るなぁ…

2019-03-05 12:55 UTC, taishi-matsumura commented on XEVIOUS/ProjectManager.cpp
> +		MessageBox(0,"DirectXの作成に失敗しまいた","",MB_OK);
タイポ。
```suggestion
		MessageBox(0,"DirectXの作成に失敗しました", "", MB_OK);
```

2019-03-05 12:55 UTC, taishi-matsumura commented on XEVIOUS/SceneManager.cpp
> +			m_pScene = NULL;
他の箇所でも指摘しましたが、直後にnewするのであればNULLを代入する意味は無いですね。

2019-03-05 12:55 UTC, taishi-matsumura commented on XEVIOUS/enumScene.h
> +};
改行入れましょう。

2019-03-05 12:55 UTC, taishi-matsumura commented on XEVIOUS/enum_Scene.h
> +};
このファイルは不要では？

2019-03-05 12:55 UTC, taishi-matsumura commented on XEVIOUS/ProjectManager.cpp
> +		return hr;
呼び出し元でエラーチェックしていませんが、もしここに来たら上の `DirectInput8Create()` で生成した `IDIRECTINPUT8` オブジェクトは誰が解放するの？

2019-03-05 12:55 UTC, taishi-matsumura commented on XEVIOUS/ProjectManager.cpp
> +		return hr;
上と同様の指摘ですが、もしここに来たら上の `DirectInput8Create()` で生成した `IDIRECTINPUT8` オブジェクトと `m_pDirectX->m_pKeyDevice` は誰が解放するの？

とかとかが他にもあると思います。
そういう流れも考えながらコード書いていきましょう。
適当なエラー処理は書かないこと。

2019-03-05 13:00 UTC, taishi-matsumura commented on XEVIOUS/DirectX.cpp
> +void DirectX::KeyGetFuncton()
早とちりしてました。
[八原への再指摘](https://github.com/human-osaka-game-2018/Shooting/pull/16#discussion_r262372587) と同様です。
ごめんなさい。

2019-03-06 03:43 UTC, taishi-matsumura requested changes

2019-03-06 03:43 UTC, taishi-matsumura commented on XEVIOUS/DirectX.cpp
> +void DirectX::KeyCaptureState()
関数名おかしいです

2019-03-06 03:53 UTC, taishi-matsumura reviewed
オッケーです。指摘是正お疲れ様でした ☕️ 
コミットが40件もあるので整理しましょう。

2019-03-06 08:00 UTC, taishi-matsumura approved these changes

2019-03-06 08:01 UTC, merged