[WIP]背景のスクロールと弾の発射 #3 #5
human-osaka-game-2018/kawahara_shooting pull request #14
Opened 2019-03-02 07:02 UTC by koujiroukawahara

2019-03-02 10:08 UTC, Harutaka-Tsujino requested changes

2019-03-02 10:08 UTC, Harutaka-Tsujino commented on XEVIOUS/GameScene.cpp
> +		BG[0].tv -= 0.01f;
for文で回してください

2019-03-05 11:11 UTC, taishi-matsumura requested changes
masterの最新からの差分が全部出るからレビューしにくい！

2019-03-05 11:11 UTC, taishi-matsumura commented on XEVIOUS/GamePlayer.cpp
> +void GamePlayer::RestrictionFrameOut()
「ステージ外にはみ出るのを制限する関数」なんだと思いますが、関数名は動詞にしましょう。(restrictionは名詞ですね)
で、主語はGamePlayerなので…どうしよう…？

用いる動詞については、GamePlayer(イコール主語なので自分自身)が「戻る」だと考えると
* go back(戻る、帰る)
* turn back(引き返す)

くらいでしょうか。

「どこに？」は、フレームは「コマ」という意味のフレーム(「1秒間に60フレーム」のフレーム)と被って紛らわしいので…なんやろ…？
* GameArea
* Lane
* Course
* Field

くらいでしょうか？(けどレーンもコースも違和感あるし、フィールドもシューティングっぽく無いしなぁ…)

とかとか考えると
`TurnBackToGameArea()` くらいかなぁ？

@yttmwork @Harutaka-Tsujino @shion-sagawa @Kinoshita-Tatsuya @ToshiyaMatsuoka 
もっと良いのがあれば提案して下さい。

2019-03-05 11:11 UTC, taishi-matsumura commented on XEVIOUS/GameScene.cpp
> +	BGScroll(m_BG);
自身のメンバ変数を引数で渡す意味が無いです。

2019-03-05 11:11 UTC, taishi-matsumura commented on XEVIOUS/GameScene.h
> +	void BGScroll(CustomVertex BG[4]);
「背景をスクロールさせる」であれば
```suggestion
	void ScrollBackground(CustomVertex BG[4]);
```
かな。

2019-03-05 11:14 UTC, taishi-matsumura commented on XEVIOUS/GamePlayer.cpp
> +void GamePlayer::RestrictionFrameOut()
GamePlayer以外のクラスがGamePlayerを押し戻すのであれば `PushBack` (押し戻す)でも良いと思いますが…

2019-03-05 11:26 UTC, taishi-matsumura commented on XEVIOUS/GameScene.cpp
> +	BGScroll(m_BG);
指摘が言葉足らずですね。すみません。

`BGScroll()` に渡されるのが常に自身のメンバ変数なのであれば、引数無しにして `BGScroll()` の中で `m_BG` を参照すれば良いのでは？
という意味です。

2019-03-05 13:04 UTC, taishi-matsumura commented
PullRequest #13 の方がゴリゴリ修正中なので、あっちがmasterにマージされるまで待った方が安全な気がします。
masterにマージされたらそこに「背景のスクロールと弾の発射」ブランチをrebaseし、そこから指摘是正を始めましょう。

というわけで、さっさと #13 を終わらせましょう！

2019-03-07 07:36 UTC, Harutaka-Tsujino requested changes

2019-03-07 07:36 UTC, Harutaka-Tsujino commented on XEVIOUS/GameBullet.cpp
> +	m_BulletIntervalCount = 0;
メンバイニシャライザを使用してください

2019-03-07 07:36 UTC, Harutaka-Tsujino commented on XEVIOUS/GameScene.cpp
> +		for (int i = 0;i < 4;i++)
なんのiかわからないので名前を考えてください

2019-03-07 07:52 UTC, taishi-matsumura requested changes

2019-03-07 07:52 UTC, taishi-matsumura commented on XEVIOUS/GamePlayer.cpp
> +void GamePlayer::PushBack()
是正NGです。指摘内容を再度確認して下さい。

2019-03-07 07:52 UTC, taishi-matsumura commented on XEVIOUS/GameScene.cpp
> +		for (int i = 0;i < 4;i++)
コレクションの要素全部に対して何かするのなら、 for each とか 範囲ベースfor文とかで回しましょう。

2019-03-07 07:52 UTC, taishi-matsumura commented on XEVIOUS/GameScene.cpp
> +	for (int i = 0;i < 4;i++)
ここも全件に対して何かするんですよね？
少なくともマジックナンバーの `4` はやめよう。

2019-03-07 08:04 UTC, ToshiyaMatsuoka commented on XEVIOUS/GameScene.cpp
> +				m_BG[i].tv = 1.0f;
`m_BG[0].tv`が`-1.0f`以下なら一定の値にするって処理ですけど、すべての`m_BG`メンバ`tv`に対して`+2.0f`で解決するような気がします

2019-03-07 08:12 UTC, ToshiyaMatsuoka commented on XEVIOUS/GameScene.cpp
> +				m_BG[i].tv = 1.0f;
`+2.0f`ではなく「一定の値を加算する」の方が正しいですね。

2019-03-07 08:41 UTC, taishi-matsumura requested changes

2019-03-07 08:41 UTC, taishi-matsumura commented on XEVIOUS/GameBullet.cpp
> +	for (auto& m_CenterBullet : m_BulletPos)
`m_` はメンバ変数用のプレフィックスですよね？
他にもありそうなので再確認して下さい。

2019-03-07 09:12 UTC, koujiroukawahara commented on XEVIOUS/GameScene.cpp
> +		BG[0].tv -= 0.01f;
なおしました

2019-03-07 09:20 UTC, taishi-matsumura requested changes

2019-03-07 09:20 UTC, taishi-matsumura commented on XEVIOUS/GamePlayer.cpp
> +	TurnbackToGameArea();
関数の意味が変わったのでコメントも直しましょう

2019-03-07 09:20 UTC, taishi-matsumura commented on XEVIOUS/GameBullet.cpp
> +	for (auto& CenterBullet : m_BulletPos)
ローカル変数はLowerCamelで統一するんじゃなかったですか？

2019-03-07 09:37 UTC, taishi-matsumura requested changes

2019-03-07 09:37 UTC, taishi-matsumura commented on XEVIOUS/GameBullet.h
> +const float BULLETSPEED = 7.f;
これは単語と単語の間に `_` 入れないの？

2019-03-07 09:40 UTC, Harutaka-Tsujino approved these changes

2019-03-07 09:40 UTC, taishi-matsumura approved these changes

2019-03-07 09:43 UTC, merged