si-nn ファイル分け
human-osaka-game-2018/kawahara_shooting pull request #15
Opened 2019-03-07 10:27 UTC by koujiroukawahara

2019-03-07 12:11 UTC, taishi-matsumura requested changes
プルリクのdescription書いて下さい

2019-03-07 12:11 UTC, taishi-matsumura commented on XEVIOUS/GameScene/Bullet/GameBullet.h
> +#include "../../DirectX.h"
ヘッダファイルの中で相対path書くのはやめましょう。
なぜ良くないのかの理由と、対策を考えて下さい。
他の生徒にも同じ指摘をしているので、わからなければ相談してみて下さい。

2019-03-08 10:49 UTC, koujiroukawahara commented on XEVIOUS/GameScene/Bullet/GameBullet.h
> +#include "../../DirectX.h"
調べて見てプロパティの設定で#includeの追加でヘッダファイルに相対パスを書かないをしたのですがこの方法だと絶対パスになってますよね？

2019-03-08 10:50 UTC, koujiroukawahara commented on XEVIOUS/GameScene/Bullet/GameBullet.h
> +#include "../../DirectX.h"
バイト行くので返信は深夜になります

2019-03-08 14:56 UTC, taishi-matsumura commented on XEVIOUS/GameScene/Bullet/GameBullet.h
> +#include "../../DirectX.h"
プロジェクトディレクトリ(vcxprojファイルがあるディレクトリ)を表すマクロがあるので、それを使えば良いと思います。
で、プロジェクトのルートをincludeディレクトリに追加したら、あとは `#include "フォルダ名/ヘッダファイル名"` でincludeできるようになるので、ソースコード内から `../` 等の相対path指定を消せるはず。

2019-03-08 15:03 UTC, taishi-matsumura commented
今回は、プルリクがマージされたと同時にissueを閉じてしまって良いはずなので、そうなるようにdescriptionを修正しておいて下さい。

2019-03-11 15:25 UTC, taishi-matsumura requested changes

2019-03-11 15:25 UTC, taishi-matsumura commented on XEVIOUS/XEVIOUS.vcxproj
> +      <AdditionalIncludeDirectories>C:\Users\jiros\OneDrive\デスクトップ\XEVIOUS\XEVIOUS\GameScene\Bullet;C:\Users\jiros\OneDrive\デスクトップ\XEVIOUS\XEVIOUS\GameScene\Player;C:\Users\jiros\OneDrive\デスクトップ\XEVI
是正NG。
これだと川原のPC以外ではビルドできなくなってしまいます。

2019-03-11 15:27 UTC, koujiroukawahara commented on XEVIOUS/XEVIOUS.vcxproj
> +      <AdditionalIncludeDirectories>C:\Users\jiros\OneDrive\デスクトップ\XEVIOUS\XEVIOUS\GameScene\Bullet;C:\Users\jiros\OneDrive\デスクトップ\XEVIOUS\XEVIOUS\GameScene\Player;C:\Users\jiros\OneDrive\デスクトップ\XEVI
このやり方って絶対pathになってますよね？

2019-03-11 15:28 UTC, taishi-matsumura commented on XEVIOUS/XEVIOUS.vcxproj
> +      <AdditionalIncludeDirectories>C:\Users\jiros\OneDrive\デスクトップ\XEVIOUS\XEVIOUS\GameScene\Bullet;C:\Users\jiros\OneDrive\デスクトップ\XEVIOUS\XEVIOUS\GameScene\Player;C:\Users\jiros\OneDrive\デスクトップ\XEVI
更に言うと、川原のPCの中でもデスクトップ以外の場所ではビルドできなくなってしまいます。

2019-03-11 15:28 UTC, taishi-matsumura commented on XEVIOUS/XEVIOUS.vcxproj
> +      <AdditionalIncludeDirectories>C:\Users\jiros\OneDrive\デスクトップ\XEVIOUS\XEVIOUS\GameScene\Bullet;C:\Users\jiros\OneDrive\デスクトップ\XEVIOUS\XEVIOUS\GameScene\Player;C:\Users\jiros\OneDrive\デスクトップ\XEVI
更に言うと、川原のPCの中でもデスクトップ以外の場所ではビルドできないね。

2019-03-11 15:39 UTC, koujiroukawahara commented on XEVIOUS/XEVIOUS.vcxproj
> +      <AdditionalIncludeDirectories>C:\Users\jiros\OneDrive\デスクトップ\XEVIOUS\XEVIOUS\GameScene\Bullet;C:\Users\jiros\OneDrive\デスクトップ\XEVIOUS\XEVIOUS\GameScene\Player;C:\Users\jiros\OneDrive\デスクトップ\XEVI
これの解決方法がわからないです

2019-03-11 16:02 UTC, taishi-matsumura commented on XEVIOUS/XEVIOUS.vcxproj
> +      <AdditionalIncludeDirectories>C:\Users\jiros\OneDrive\デスクトップ\XEVIOUS\XEVIOUS\GameScene\Bullet;C:\Users\jiros\OneDrive\デスクトップ\XEVIOUS\XEVIOUS\GameScene\Player;C:\Users\jiros\OneDrive\デスクトップ\XEVI
DirectXのインストールディレクトリも `DXSDK_DIR` を使用するよう前期から言っていますが、それと同様です。
このダイアログの「マクロ」ボタンをクリックすると使用可能なマクロが出てくるので、プロジェクトのルートを指すマクロを使えば良いのではないでしょうか。
![image](https://user-images.githubusercontent.com/12269762/54138148-4795e380-4462-11e9-943f-8c098a2df948.png)

2019-03-11 16:04 UTC, taishi-matsumura commented on XEVIOUS/XEVIOUS.vcxproj
> +      <AdditionalIncludeDirectories>C:\Users\jiros\OneDrive\デスクトップ\XEVIOUS\XEVIOUS\GameScene\Bullet;C:\Users\jiros\OneDrive\デスクトップ\XEVIOUS\XEVIOUS\GameScene\Player;C:\Users\jiros\OneDrive\デスクトップ\XEVI
ふと気になって、DirectXのヘッダファイルやライブラリのディレクトリの指定方法を確認しましたが、そっちもダメですね。
DirectXのSDKをDドライブにインストールしている人のPCではビルドできませんよね。

2019-03-11 16:19 UTC, taishi-matsumura commented on XEVIOUS/XEVIOUS.vcxproj
> +      <AdditionalIncludeDirectories>C:\Users\jiros\OneDrive\デスクトップ\XEVIOUS\XEVIOUS\GameScene\Bullet;C:\Users\jiros\OneDrive\デスクトップ\XEVIOUS\XEVIOUS\GameScene\Player;C:\Users\jiros\OneDrive\デスクトップ\XEVI
使用可能なマクロは大量にあるのでギョッとすると思いますが、 `visual studio プロジェクト マクロ` 等でググると説明してくれているサイトがたくさんあるので調べてみて下さい。

また、併せて「環境変数」についても知っておいて下さい。
AutoDeskのFBX SDKを使っているクラスメイトは、FBX SDKのインストールディレクトリを各自のPCの環境変数に設定して使用しているようです。
この辺りのPCの基礎知識が無いとみんなの話に付いていけませんよ。

2019-03-12 08:51 UTC, taishi-matsumura approved these changes

2019-03-12 08:52 UTC, merged