[WIP]敵機の描画と当たり判定
human-osaka-game-2018/kawahara_shooting pull request #18
Opened 2019-03-15 13:38 UTC by koujiroukawahara

- [ ] 敵機の描画
- [ ] 敵機に当たり判定を付ける

2019-03-18 08:40 UTC, Harutaka-Tsujino commented on XEVIOUS/GameEnemy.cpp
> +	for (auto& centerEnemy : m_EnemyPos)
```suggestion
	for (auto& enemyCenter: m_EnemyCenter)
```

2019-03-18 08:43 UTC, Harutaka-Tsujino commented on XEVIOUS/GameEnemy.cpp
> +					moveDirection.y += 3.f;
後に単位ベクトル化をを行うのなら3,6を扱うのではなくて
1,2のほうがいいと思います

2019-03-18 08:45 UTC, koujiroukawahara commented on XEVIOUS/GameEnemy.cpp
> +	for (auto& centerEnemy : m_EnemyPos)
このvevtor名さぁー
今思ったらpos以外にも種類、移動パターン、HP、出現する時間みたいな感じで
Enemyの情報持ってるんやけどCentersでもおかしない？

2019-03-18 08:45 UTC, Harutaka-Tsujino commented on XEVIOUS/GameEnemy.cpp
> +					moveDirection.y += 3.f;
また移動ベクトルを回転させたほうがキー入力などを扱わない場合綺麗に見えると思います

2019-03-18 08:47 UTC, koujiroukawahara commented on XEVIOUS/GameEnemy.cpp
> +					moveDirection.y += 3.f;
移動ベクトルの回転はちょっとわからんけど1個目の指摘はもう直しました

2019-03-18 08:47 UTC, Harutaka-Tsujino commented on XEVIOUS/GameEnemy.cpp
> +			moveDirection *= 3;
コメントを入れて移動量を３倍にしていることを明示的に示しましょう

2019-03-18 08:48 UTC, koujiroukawahara commented on XEVIOUS/GameEnemy.cpp
> +			moveDirection *= 3;
それの定数にしてるからちょっと待って

2019-03-18 08:49 UTC, koujiroukawahara commented on XEVIOUS/GameEnemy.cpp
> +			moveDirection *= 3;
今からコミットするやつで指摘してほしい

2019-03-18 08:49 UTC, Harutaka-Tsujino commented on XEVIOUS/GameEnemy.h
> +};
改行を行ってください

2019-03-18 08:50 UTC, koujiroukawahara commented on XEVIOUS/GameEnemy.h
> +};
すいません
なおしました

2019-03-18 08:51 UTC, Harutaka-Tsujino commented on XEVIOUS/GameEnemy.h
> +		float x = 0.f;
ここ小文字になっているので統一しましょう

2019-03-18 08:53 UTC, Harutaka-Tsujino commented on XEVIOUS/GameEnemy.cpp
> +					m_pDirectX->InitSquareCustomVertex(m_EnemyData.Enemy, m_EnemyData.x, m_EnemyData.y,32);
32と64が何かわかりません

2019-03-18 08:55 UTC, Harutaka-Tsujino commented on XEVIOUS/GameEnemy.cpp
> +	for (auto& centerEnemy : m_EnemyPos)
m_enemies等がいいと思います

2019-03-18 08:58 UTC, Harutaka-Tsujino commented on XEVIOUS/GameEnemy.cpp
> +				ENEMY_MOVE_SPEED = 4.f;
```suggestion
				enemySpeed = 4.f;
```
constと紛らわしいので変数名を修正したほうがいいと思います
また速さが全エネミー共通なので値を変える必要はないのでは

2019-03-18 09:01 UTC, Harutaka-Tsujino commented on XEVIOUS/GameEnemy.cpp
> +		if (centerEnemy.AppearCount >= centerEnemy.AppearTime * 60)
AppearTimeが分か秒なのかが分からないです

2019-03-18 09:07 UTC, taishi-matsumura requested changes
言い出したらキリ無いので、あとは辻野と松岡に任せます

2019-03-18 09:07 UTC, taishi-matsumura commented on XEVIOUS/GameEnemy.cpp
> +		if (centerEnemy.AppearCount >= centerEnemy.AppearTime * 60)
if文の中身、他でも使っているようなので関数化してしまいましょう。

2019-03-18 09:07 UTC, taishi-matsumura commented on XEVIOUS/GameEnemy.cpp
> +					}
このswtich-caseは無いわー 💩

2019-03-18 09:27 UTC, koujiroukawahara commented on XEVIOUS/GameEnemy.cpp
> +	for (auto& centerEnemy : m_EnemyPos)
それにするわ

2019-03-18 09:29 UTC, koujiroukawahara commented on XEVIOUS/GameEnemy.cpp
> +				ENEMY_MOVE_SPEED = 4.f;
もしconstにしたらエネミーによって動く速さを変えたい場合どうするん？

2019-03-18 09:34 UTC, koujiroukawahara commented on XEVIOUS/GameEnemy.cpp
> +		if (centerEnemy.AppearCount >= centerEnemy.AppearTime * 60)
秒やからsecondを付けた方がいいってこと？
あとこれ変数は何秒後に出現するって意味で出現時間って名前つけてるんやけど
これやったら敵機が出現してる間の時間って意味に捉えるくない？

2019-03-18 09:34 UTC, koujiroukawahara commented on XEVIOUS/GameEnemy.cpp
> +		if (centerEnemy.AppearCount >= centerEnemy.AppearTime * 60)
1文だけでも関数化いれますか？

2019-03-18 09:37 UTC, koujiroukawahara commented on XEVIOUS/GameEnemy.cpp
> +					}
switch文のなかのboolを切り替えてるswitch文が糞なんですよね？

2019-03-18 09:42 UTC, koujiroukawahara commented on XEVIOUS/GameEnemy.h
> +		float x = 0.f;
修正しました

2019-03-18 09:42 UTC, taishi-matsumura commented on XEVIOUS/GameEnemy.cpp
> +					}
yes

2019-03-18 09:44 UTC, taishi-matsumura commented on XEVIOUS/GameEnemy.cpp
> +		if (centerEnemy.AppearCount >= centerEnemy.AppearTime * 60)
こういう「何を判断してるのかよくわからない処理」こそ名前を付けて関数化すべきです。
行数は関係無いです。

実際、辻野と松岡も「これ、何を判定してるんや？」と言ってたよ。

2019-03-18 09:47 UTC, koujiroukawahara commented on XEVIOUS/GameEnemy.cpp
> +					m_pDirectX->InitSquareCustomVertex(m_EnemyData.Enemy, m_EnemyData.x, m_EnemyData.y,32);
サイズなのでconstに定数を追加したんやけど
基本サイズが32なんやけど２倍の大きさの敵機の値は(ENEMY_SIZE * 2)みたい感じでいいんかな？

2019-03-18 09:47 UTC, taishi-matsumura commented on XEVIOUS/GameEnemy.cpp
> +					}
switch-caseではなくif-elseにすべきですね。
さらに言うと、booleanの変数の中身を反転させる処理はif文使わなくても1行で書けます。

2019-03-18 09:49 UTC, koujiroukawahara commented on XEVIOUS/GameEnemy.cpp
> +					}
僕もこの処理は 💩と思ってたので直します

2019-03-18 09:50 UTC, koujiroukawahara commented on XEVIOUS/GameEnemy.cpp
> +				ENEMY_MOVE_SPEED = 4.f;
ごめんこの質問なしで

2019-03-18 09:51 UTC, Harutaka-Tsujino commented on XEVIOUS/GameEnemy.cpp
> +		if (centerEnemy.AppearCount >= centerEnemy.AppearTime * 60)
出現までにかかる時間_secとかかかる秒とかにしたらどう？

2019-03-18 09:52 UTC, Harutaka-Tsujino commented on XEVIOUS/GameEnemy.cpp
> +				ENEMY_MOVE_SPEED = 4.f;
const じゃない変数を大文字で書かないようにしようということですね

2019-03-18 09:53 UTC, Harutaka-Tsujino commented on XEVIOUS/GameEnemy.cpp
> +					m_pDirectX->InitSquareCustomVertex(m_EnemyData.Enemy, m_EnemyData.x, m_EnemyData.y,32);
ENEMY_DEFAULT_SIZE * 2.0fとかならいいと思うで

2019-03-18 09:53 UTC, koujiroukawahara commented on XEVIOUS/GameEnemy.cpp
> +				ENEMY_MOVE_SPEED = 4.f;
おけおけ

2019-03-18 09:53 UTC, koujiroukawahara commented on XEVIOUS/GameEnemy.cpp
> +		if (centerEnemy.AppearCount >= centerEnemy.AppearTime * 60)
_secの意味って何？

2019-03-18 09:54 UTC, Harutaka-Tsujino commented on XEVIOUS/GameEnemy.cpp
> +		if (centerEnemy.AppearCount >= centerEnemy.AppearTime * 60)
second(秒)やで

2019-03-18 09:55 UTC, Harutaka-Tsujino commented on XEVIOUS/GameEnemy.h
> +		float x = 0.f;
プッシュしてください

2019-03-18 09:56 UTC, ToshiyaMatsuoka commented on XEVIOUS/GameEnemy.cpp
> +	int c, i = 0, x = 0, y = 0;
これらのたった1字しかない変数名が何を指しているのか
変数名だけで理解できないです。

2019-03-18 09:56 UTC, ToshiyaMatsuoka commented on XEVIOUS/GameEnemy.cpp
> +			if (x == APPEARTIME)
`Switch`で振り分ければ良いのでは？

2019-03-18 09:56 UTC, ToshiyaMatsuoka commented on XEVIOUS/GameEnemy.cpp
> +						centerEnemy.MovementChangeCount = 0;
どう条件分岐しようが同一の処理をするのなら、
分岐の前後のどちらか一箇所に書けばよいのでは？

2019-03-18 09:56 UTC, ToshiyaMatsuoka commented on XEVIOUS/GameEnemy.cpp
> +	while ((c = getc(fp)) != EOF)
c言語の関数ではなく、C++のSTLを使いましょう

2019-03-18 09:56 UTC, ToshiyaMatsuoka commented on XEVIOUS/GameEnemy.cpp
> +		centerEnemy.AppearCount++;
`Render`で`centerEnemy.AppearCount++;`をしなければならない意味は何でしょう？
描画関数内で描画すること以外の関係のない処理が入っているのが気持ち悪いです。

2019-03-18 09:57 UTC, koujiroukawahara commented on XEVIOUS/GameEnemy.h
> +		float x = 0.f;
わかったww

2019-03-18 10:07 UTC, koujiroukawahara commented on XEVIOUS/GameEnemy.cpp
> +			if (x == APPEARTIME)
確かに

2019-03-18 10:15 UTC, koujiroukawahara commented on XEVIOUS/GameEnemy.cpp
> +	int c, i = 0, x = 0, y = 0;
int csvData = 0, i = 0, csvx = 0, csvy = 0;
こんな感じでいいんかな？

2019-03-18 10:37 UTC, koujiroukawahara commented on XEVIOUS/GameEnemy.cpp
> +						centerEnemy.MovementChangeCount = 0;
なおしました

2019-03-18 10:37 UTC, koujiroukawahara commented on XEVIOUS/GameEnemy.cpp
> +			if (x == APPEARTIME)
なおしました

2019-03-18 10:41 UTC, koujiroukawahara commented on XEVIOUS/GameEnemy.cpp
> +		centerEnemy.AppearCount++;
確かに
Updataの方に書きます

2019-03-18 10:47 UTC, ToshiyaMatsuoka commented on XEVIOUS/GameEnemy.cpp
> +	int c, i = 0, x = 0, y = 0;
`i`以外はそのような感じでいいと思います。
関数の頭で一文字のローカル変数を出された場合に、
それがどこでどのように使われる変数であるのかがすぐに判断できません。

誰にでも理解のしやすい名称を付けるようにしていくべきです。
でないとその変数でなにかバグが起きた場合に共同作業者が何が悪かったのか調べるのにかなりの時間を取られることになります。
それはただの共同作業への負担にしかなりません。

2019-03-18 10:48 UTC, ToshiyaMatsuoka commented on XEVIOUS/GameEnemy.cpp
> +			if (x == APPEARTIME)
プッシュしてから修正した旨のコメントを残してください

2019-03-18 13:06 UTC, taishi-matsumura commented
描画だけでだいぶ量増えてきたので、当たり判定は別PRでやりましょかー

2019-03-18 14:08 UTC, Harutaka-Tsujino commented on XEVIOUS/GameEnemy.cpp
> +	for (auto& centerEnemy : m_Enemie)
Enemyの複数形がEnemiesなのでここはスペルミスですね

2019-03-19 02:18 UTC, koujiroukawahara commented on XEVIOUS/GameEnemy.cpp
> +	for (auto& centerEnemy : m_Enemie)
なおしました

2019-03-19 21:36 UTC, koujiroukawahara commented on XEVIOUS/GameEnemy.cpp
> +	while ((c = getc(fp)) != EOF)
変更しました

2019-03-19 22:11 UTC, koujiroukawahara commented on XEVIOUS/GameEnemy.cpp
> +		if (centerEnemy.AppearCount >= centerEnemy.AppearTime * 60)
関数化しました

2019-03-20 05:15 UTC, ToshiyaMatsuoka commented on XEVIOUS/GameEnemy.cpp
> +using namespace std;
usingディレクティブ使うのはまあいいのですが。
それなら`std::`をコード上で使わないでください

2019-03-20 05:15 UTC, ToshiyaMatsuoka commented on XEVIOUS/GameEnemy.cpp
> +bool GameEnemy::BeOverAppearTime(InfoEnemy enemies)
名前から何をしているかよくわからないので、
どういった意味なのか教えてください。

2019-03-20 05:15 UTC, ToshiyaMatsuoka commented on XEVIOUS/GameEnemy.cpp
> +	for (auto& centerEnemy : m_Enemies)
`centerEnemy `って真ん中とか以外の内容を含んでいませんか？
意味が合わないので名称を変更するべきだと思います。

2019-03-20 05:27 UTC, taishi-matsumura commented on XEVIOUS/GameEnemy.cpp
> +using namespace std;
usingディレクティブやめてusing宣言にしましょう。
後期のテスト範囲やで？

2019-03-20 05:35 UTC, taishi-matsumura requested changes

2019-03-20 05:35 UTC, taishi-matsumura commented on XEVIOUS/GameEnemy.cpp
> +					}
間違いでは無いし丁寧なコードだと思いますが、今回は
> さらに言うと、booleanの変数の中身を反転させる処理はif文使わなくても1行で書けます。

をやってみて下さい。

2019-03-20 08:35 UTC, koujiroukawahara commented on XEVIOUS/GameEnemy.cpp
> +using namespace std;
usingディレクトリ消すの忘れてました

2019-03-20 08:39 UTC, koujiroukawahara commented on XEVIOUS/GameEnemy.cpp
> +bool GameEnemy::BeOverAppearTime(InfoEnemy enemies)
be over fortyで40歳を超えているやったからbe over appeartimeで出現時間を超えてるになるかな？って思って

2019-03-20 08:43 UTC, koujiroukawahara commented on XEVIOUS/GameEnemy.cpp
> +	for (auto& centerEnemy : m_Enemies)
なおしてみました

2019-03-20 08:44 UTC, koujiroukawahara commented on XEVIOUS/GameEnemy.cpp
> +					}
了解です

2019-03-20 08:48 UTC, taishi-matsumura commented on XEVIOUS/GameEnemy.cpp
> +bool GameEnemy::BeOverAppearTime(InfoEnemy enemies)
それ、命令形やな

2019-03-20 08:49 UTC, taishi-matsumura commented on XEVIOUS/GameEnemy.cpp
> +using namespace std;
ディレクティブ、な。
全然意味違うよ。

2019-03-21 12:30 UTC, koujiroukawahara commented on XEVIOUS/GameEnemy.cpp
> +bool GameEnemy::BeOverAppearTime(InfoEnemy enemies)
この意味ってもうちょっと調べろであってますよね？

2019-03-21 13:32 UTC, taishi-matsumura commented on XEVIOUS/GameEnemy.cpp
> +bool GameEnemy::BeOverAppearTime(InfoEnemy enemies)
「勤勉でありなさい、辛抱強くありなさい」かな。

2019-03-21 13:35 UTC, taishi-matsumura commented on XEVIOUS/GameEnemy.cpp
> +using namespace std;
f8c649e 、確認しました。
せっかくなのでusing宣言使ってみて下さい。

2019-03-21 13:37 UTC, taishi-matsumura commented on XEVIOUS/GameEnemy.cpp
> +					}
確認しました。
これがベストというわけでは無いですが、よく見かける形なので読み書きできるようになっておいてね。

2019-03-21 13:54 UTC, taishi-matsumura requested changes

2019-03-21 13:54 UTC, taishi-matsumura commented on XEVIOUS/GameEnemy.cpp
> +	for (auto& infoEnemy : m_Enemies)
「 `m_Enemies` の中から一個取り出したもの」だから `enemy` で良いと思う。
それで違和感が出るのであれば、そもそも `m_Enemies` が良くないのでしょう。

2019-03-21 17:13 UTC, koujiroukawahara commented on XEVIOUS/GameEnemy.cpp
> +	for (auto& infoEnemy : m_Enemies)
多分これで全部の修正したのでマージお願いします

2019-03-22 09:26 UTC, taishi-matsumura requested changes
まだまだですね

2019-03-22 09:26 UTC, taishi-matsumura commented on XEVIOUS/GameEnemy.cpp
> +			m_pDirectX->DrawTexture("GAME_ENEMY_TEX", enemy.Enemy);
`enemy.Enemy` って違和感ありませんか？
なぜ違和感が出るかと言うと `m_Enemies` がそもそも変なんでしょうね。

2019-03-22 09:26 UTC, taishi-matsumura commented on XEVIOUS/GameEnemy.cpp
> +bool GameEnemy::OverTheTimeLimit(InfoEnemy enemies)
戻り値がbooleanの関数名としてはNGです

2019-03-22 09:49 UTC, koujiroukawahara commented on XEVIOUS/GameEnemy.cpp
> +bool GameEnemy::OverTheTimeLimit(InfoEnemy enemies)
OverTheAppearCountではどうでしょうか？

2019-03-22 10:13 UTC, taishi-matsumura commented on XEVIOUS/GameEnemy.cpp
> +bool GameEnemy::OverTheTimeLimit(InfoEnemy enemies)
`bool 関数 命名` とかでググって調べて下さい。
[こんなサイト](https://qiita.com/Ted-HM/items/7dde25dcffae4cdc7923#%E7%9C%9F%E5%81%BD%E5%80%A4)がヒットすると思うので頑張って読みましょう。
それを踏まえて名前を考えて提案して下さい。

2019-03-22 10:31 UTC, koujiroukawahara commented on XEVIOUS/GameEnemy.cpp
> +	for (auto& infoEnemy : m_Enemies)
m_Enemiesの所は（エネミー達のステータス）という意味でm_EnemiesOfStatusにして
範囲for文の所は（エネミー1機のステータス）という意味でm_EnemyOfStatusにしてみたんですが似ていて間違えそうじゃないですか？
あとパラメータとも迷ったのですが正直どちらでもいいいかな？って思うのですがどうでしょうか？

2019-03-22 10:44 UTC, taishi-matsumura commented on XEVIOUS/GameEnemy.cpp
> +	for (auto& infoEnemy : m_Enemies)
`for (auto 単数形 : 複数形)` という書き方はよくやりますが、範囲forの一時変数はstatusとかでもいいかも知れないですね。

`m_EnemiesOfStatus` は英語的におかしいです。

2019-03-22 10:55 UTC, taishi-matsumura commented
https://github.com/human-osaka-game-2018/kawahara_shooting/pull/18#discussion_r267758499 の件はどうなりましたか？
後期のテスト範囲なので復習して下さい。 [C++その3](https://taishi-matsumura.github.io/exam/CPP_paper_3/index.html) の①ですね。

2019-03-22 13:38 UTC, taishi-matsumura requested changes
もう指摘しないでおこうと思っていましたが…

2019-03-22 13:38 UTC, taishi-matsumura commented on XEVIOUS/GameEnemy.cpp
> +				}
`m_MovementChange` がtrueのときとfalseのときが両方同時に発生することは無いはずなので、 if/else にしてしまいましょう。
あと、 `moveDirection.y += 2.f;` と `m_EnemyMoveSpeed = 4.f;` は共通なので2箇所に書く必要は無いよね。

2019-03-22 13:38 UTC, taishi-matsumura commented on XEVIOUS/GameEnemy.cpp
> +				break;
違いは `InitSquareCustomVertex()` の第4引数だけなので、それを各caseで変数に入れて、 `InitSquareCustomVertex()` の呼び出しはswitch/caseの外でやってはいかがでしょうか。
「NORMAL1とNORMAL2で何が違うのかな？」と思って頑張って読んだ結果「なんや、 `ENEMY_SIZE` か `ENEMY_SIZE * 2.f` かの違いだけかよ！」ってなってガッカリします。

2019-03-22 13:38 UTC, taishi-matsumura commented on XEVIOUS/GameEnemy.cpp
> +	return false;
`enemyOfStatus.AppearTimeSec * 60` が何の値なのかわからないので、これに名前付けて変数入れましょう。
そうするとこの関数は
```
int XXX = enemyOfStatus.AppearTimeSec * 60;    // XXXの名前は考えて下さい
return enemyOfStatus.AppearCount >= XXX;
```
と書けるようになって、if文が消えてスッキリするはず。

2019-03-22 14:40 UTC, koujiroukawahara commented on XEVIOUS/GameEnemy.cpp
> +using namespace std;
ごめんなさい
忘れてました
やります

2019-03-22 19:31 UTC, koujiroukawahara commented on XEVIOUS/GameEnemy.cpp
> +	for (auto& infoEnemy : m_Enemies)
範囲for文はstatusで変えます
m_EnemiesOfStatusの方はm_EnemyStatusesでどうですか？

2019-03-22 19:35 UTC, koujiroukawahara commented on XEVIOUS/GameEnemy.cpp
> +bool GameEnemy::OverTheTimeLimit(InfoEnemy enemies)
AppearCountI Is More Thanでどうでしょう？

2019-03-22 19:44 UTC, koujiroukawahara commented on XEVIOUS/GameEnemy.cpp
> +				}
確かに同時発生はないのでekseにします
共通部分の2行減るのでそうします

2019-03-22 19:53 UTC, koujiroukawahara commented on XEVIOUS/GameEnemy.cpp
> +				break;
float size;
				switch (m_EnemyData.Type)
				{
				case NORMAL:
					　　　size = ENEMY_SIZE;
					　　　break;
				case NORMAL2:
					　　　size = ENEMY_SIZE * 2.f;
					　　　break;
				}
m_pDirectX->InitSquareCustomVertex(m_EnemyData.Enemy, m_EnemyData.X, m_EnemyData.Y, size);
				break;

こんな感じで大丈夫ですか？caseの中がスッキリしたと思います

2019-03-22 20:12 UTC, koujiroukawahara commented on XEVIOUS/GameEnemy.cpp
> +	return false;
この1文で真偽のreturnできるのが初めて知りました
2行になって凄い減りました

2019-03-23 01:33 UTC, koujiroukawahara commented on XEVIOUS/GameEnemy.cpp
> +using namespace std;
using宣言に変更しました

2019-03-23 08:25 UTC, Harutaka-Tsujino commented on XEVIOUS/GameEnemy.cpp
> +bool GameEnemy::OverTheTimeLimit(InfoEnemy enemies)
https://qiita.com/yskszk/items/5a7f99c974773f03a82a

2019-03-23 08:35 UTC, koujiroukawahara commented on XEVIOUS/GameEnemy.cpp
> +bool GameEnemy::OverTheTimeLimit(InfoEnemy enemies)
これは指摘は妥協案が出て最新のpushに書いてるはずやから見てみて

2019-03-23 16:53 UTC, taishi-matsumura approved these changes
`EnemyStatus` が実質的には `Enemy` で、 敵を複数保持している `Enemy` クラスは言ってみれば「EnemyManager」みたいなものなんですね。
だから `Enemy::CanAppear()` に違和感あるのか…
別でやりましょうか。

このPRは一旦承認しておきます。

2019-03-23 18:58 UTC, merged